// pages/valorant/bracket.js
import React from "react";
import mongoose from "mongoose";
import styles from "../../styles/Rankings.module.css";
import Bracket16 from "../../components/Bracket16";
import LosersBracket16 from "../../components/LosersBracket16";
import GrandFinalCenter from "../../components/GrandFinalCenter";

import { connectToDatabase } from "../../lib/mongodb";
import Tournament from "../../models/Tournament";
import Player from "../../models/Player";

// Tournament id used in admin (/admin/brackets/[id])
const TID = "VALO-SOLO-SKIRMISH-1";

// ===== SERVER SIDE: load published bracket + players =====
export async function getServerSideProps() {
  await connectToDatabase();

  const tournamentId = TID;

  const t = await Tournament.findOne({ tournamentId }).lean();

  if (!t || !t.bracket || !t.bracket.isPublished) {
    return {
      props: {
        tournamentId,
        published: false,
        bracket: null,
        players: [],
      },
    };
  }

  const bracket = t.bracket;

  // Collect all playerIds
  const idSet = new Set();

  (bracket.rounds || []).forEach((r) => {
    (r.matches || []).forEach((m) => {
      if (m.player1Id) idSet.add(m.player1Id.toString());
      if (m.player2Id) idSet.add(m.player2Id.toString());
      if (m.winnerId) idSet.add(m.winnerId.toString());
    });
  });

  (bracket.losersRounds || []).forEach((r) => {
    (r.matches || []).forEach((m) => {
      if (m.player1Id) idSet.add(m.player1Id.toString());
      if (m.player2Id) idSet.add(m.player2Id.toString());
      if (m.winnerId) idSet.add(m.winnerId.toString());
    });
  });

  ["winnersFinal", "losersFinal", "grandFinal"].forEach((key) => {
    const fin = bracket[key];
    if (fin) {
      if (fin.player1Id) idSet.add(fin.player1Id.toString());
      if (fin.player2Id) idSet.add(fin.player2Id.toString());
      if (fin.winnerId) idSet.add(fin.winnerId.toString());
    }
  });

  const ids = Array.from(idSet);
  let playerDocs = [];
  if (ids.length > 0) {
    const objectIds = ids.map((id) => new mongoose.Types.ObjectId(id));
    playerDocs = await Player.find({ _id: { $in: objectIds } }).lean();
  }

  const players = playerDocs.map((p) => {
    const reg = (p.registeredFor || []).find(
      (r) => r.tournamentId === tournamentId
    );

    return {
      _id: p._id.toString(),
      username: p.username || "",
      ign: reg?.ign || "",
    };
  });

  return {
    props: {
      tournamentId,
      published: true,
      bracket: JSON.parse(
        JSON.stringify({
          rounds: bracket.rounds || [],
          losersRounds: bracket.losersRounds || [],
          winnersFinal: bracket.winnersFinal || null,
          losersFinal: bracket.losersFinal || null,
          grandFinal: bracket.grandFinal || null,
        })
      ),
      players,
    },
  };
}

// ===== HELPER =====
function buildIdToLabel(players) {
  const idToLabel = {};
  for (const p of players || []) {
    idToLabel[p._id] = p.ign || p.username || "Unknown";
  }
  return idToLabel;
}

export default function BracketPage({
  tournamentId,
  published,
  bracket,
  players,
}) {
  const capacity = 16;
  const registered = players.length;
  const remaining = Math.max(capacity - registered, 0);
  const slotsText = `${registered} / ${capacity}`;
  const statusText =
    registered >= capacity ? "Full — waitlist" : `Open — ${remaining} left`;

  if (!published) {
    return (
      <div className={styles.shell}>
        <div className={styles.contentWrap}>
          <div className={styles.infoCard}>
            <h2 className={styles.tournamentTitle}>Bracket Pending</h2>
            <p style={{ color: "#8b9bb4" }}>
              This bracket is currently being generated by admins.
            </p>
          </div>
        </div>
      </div>
    );
  }

  const idToLabel = buildIdToLabel(players);
  const getLabel = (id) => (id ? idToLabel[id] || "TBD" : "TBD");

  const padNames = (arr, targetLen) => {
    const out = [...(arr || [])];
    while (out.length < targetLen) out.push("TBD");
    return out;
  };

  // --- MAPPINGS (Unchanged logic) ---
  const rounds = bracket?.rounds || [];
  const r1Matches =
    (rounds.find((r) => r.roundNumber === 1 && r.type === "winners") || {})
      .matches || [];
  const r2Matches =
    (rounds.find((r) => r.roundNumber === 2 && r.type === "winners") || {})
      .matches || [];
  const r3Matches =
    (rounds.find((r) => r.roundNumber === 3 && r.type === "winners") || {})
      .matches || [];

  const leftR16 = [],
    rightR16 = [];
  r1Matches.forEach((m, index) => {
    const pair = [getLabel(m.player1Id), getLabel(m.player2Id)];
    index < 4 ? leftR16.push(pair) : rightR16.push(pair);
  });
  while (leftR16.length < 4) leftR16.push(["TBD", "TBD"]);
  while (rightR16.length < 4) rightR16.push(["TBD", "TBD"]);

  const leftQF = [],
    rightQF = [];
  r2Matches.forEach((m, index) => {
    const pair = [getLabel(m.player1Id), getLabel(m.player2Id)];
    index < 2 ? leftQF.push(pair) : rightQF.push(pair);
  });
  while (leftQF.length < 2) leftQF.push(["TBD", "TBD"]);
  while (rightQF.length < 2) rightQF.push(["TBD", "TBD"]);

  let leftSF = ["TBD", "TBD"],
    rightSF = ["TBD", "TBD"];
  if (r3Matches[0])
    leftSF = [getLabel(r3Matches[0].player1Id), getLabel(r3Matches[0].player2Id)];
  if (r3Matches[1])
    rightSF = [getLabel(r3Matches[1].player1Id), getLabel(r3Matches[1].player2Id)];

  const winnersFinal = bracket?.winnersFinal || null;
  let finalLeft = "TBD",
    finalRight = "TBD",
    finalChamp = "TBD";
  if (winnersFinal) {
    if (winnersFinal.player1Id) finalLeft = getLabel(winnersFinal.player1Id);
    if (winnersFinal.player2Id) finalRight = getLabel(winnersFinal.player2Id);
    if (winnersFinal.winnerId) finalChamp = getLabel(winnersFinal.winnerId);
  }

  const bracketData = {
    left: { R16: leftR16, QF: leftQF, SF: leftSF },
    right: { R16: rightR16, QF: rightQF, SF: rightSF },
    final: { left: finalLeft, right: finalRight, champion: finalChamp },
  };

  const losersRounds = bracket?.losersRounds || [];
  const getLbRound = (n) =>
    (losersRounds.find((r) => r.roundNumber === n && r.type === "losers") || {
      matches: [],
    }).matches;
  const lb_r1 = padNames(
    (getLbRound(1) || []).map((m) => [
      getLabel(m.player1Id),
      getLabel(m.player2Id),
    ]),
    4
  );
  const lb_r2 = padNames(
    (getLbRound(2) || []).map((m) => [
      getLabel(m.player1Id),
      getLabel(m.player2Id),
    ]),
    4
  );
  const lb_r3a = padNames(
    (getLbRound(3) || []).map((m) => [
      getLabel(m.player1Id),
      getLabel(m.player2Id),
    ]),
    2
  );
  const lb_r3b = padNames(
    (getLbRound(4) || []).map((m) => [
      getLabel(m.player1Id),
      getLabel(m.player2Id),
    ]),
    2
  );
  const lb_r4 = padNames(
    (getLbRound(5) || []).map((m) => [
      getLabel(m.player1Id),
      getLabel(m.player2Id),
    ]),
    1
  );

  const losersFinal = bracket?.losersFinal || null;
  const lb_final =
    losersFinal && (losersFinal.player1Id || losersFinal.player2Id)
      ? [getLabel(losersFinal.player1Id), getLabel(losersFinal.player2Id)]
      : ["TBD", "TBD"];
  const lb_winner = losersFinal?.winnerId ? getLabel(losersFinal.winnerId) : "TBD";

  const grandFinal = bracket?.grandFinal || null;
  const wbFinalWinner = winnersFinal?.winnerId
    ? getLabel(winnersFinal.winnerId)
    : "TBD";
  const lbFinalWinner = lb_winner;
  const grandChampion = grandFinal?.winnerId
    ? getLabel(grandFinal.winnerId)
    : "TBD";

  // --- RANKING LOGIC ---
  const getLoserNames = (matches) => {
    return (matches || [])
      .filter((m) => m.winnerId)
      .map((m) =>
        getLabel(m.winnerId === m.player1Id ? m.player2Id : m.player1Id)
      );
  };

  const placements = {
    first: grandFinal?.winnerId ? getLabel(grandFinal.winnerId) : "TBD",
    second: grandFinal?.winnerId
      ? getLabel(
          grandFinal.winnerId === grandFinal.player1Id
            ? grandFinal.player2Id
            : grandFinal.player1Id
        )
      : "TBD",
    third: losersFinal?.winnerId
      ? getLabel(
          losersFinal.winnerId === losersFinal.player1Id
            ? losersFinal.player2Id
            : losersFinal.player1Id
        )
      : "TBD",
    fourth: getLoserNames(getLbRound(5))[0] || "TBD",
    fifthToSixth: padNames(getLoserNames(getLbRound(4)), 2),
    seventhToEighth: padNames(getLoserNames(getLbRound(3)), 2),
    ninthToTwelfth: padNames(getLoserNames(getLbRound(2)), 4),
    thirteenthToSixteenth: padNames(getLoserNames(getLbRound(1)), 4),
  };

  return (
    <div className={styles.shell}>
      {/* ===== HEADER + RANKINGS + GRAND FINAL (NORMAL WIDTH) ===== */}
      <div className={styles.contentWrap}>
        <div className={styles.headerGrid}>
          {/* LEFT: Info Card */}
          <div className={styles.infoCard}>
            <h2 className={styles.tournamentTitle}>Championship Bracket</h2>
            <div className={styles.tournamentSubtitle}>
              // 16 PLAYERS • DOUBLE ELIMINATION
            </div>

            <div className={styles.statsGrid}>
              <div className={styles.statBox}>
                <span className={styles.statLabel}>Registration</span>
                <span className={styles.statValue}>{slotsText}</span>
              </div>
              <div className={styles.statBox}>
                <span className={styles.statLabel}>Status</span>
                <span
                  className={`${styles.statValue} ${styles.statValueHighlight}`}
                >
                  LIVE
                </span>
              </div>
              <div className={styles.statBox}>
                <span className={styles.statLabel}>Stream</span>
                <span className={styles.statValue}>5TQ_TV</span>
              </div>
              <div className={styles.statBox}>
                <span className={styles.statLabel}>Format</span>
                <span className={styles.statValue}>Standard</span>
              </div>
            </div>
          </div>

          {/* RIGHT: Rankings */}
          <div className={styles.rankingContainer}>
            <div className={styles.rankingHeader}>
              <span>Place</span>
              <span>Player</span>
            </div>

            <div className={styles.rankRow}>
              <div className={`${styles.rankBadge} ${styles.gold}`}>1st</div>
              <div className={styles.rankName}>{placements.first}</div>
            </div>
            <div className={styles.rankRow}>
              <div className={`${styles.rankBadge} ${styles.silver}`}>2nd</div>
              <div className={styles.rankName}>{placements.second}</div>
            </div>
            <div className={styles.rankRow}>
              <div className={`${styles.rankBadge} ${styles.bronze}`}>3rd</div>
              <div className={styles.rankName}>{placements.third}</div>
            </div>
            <div className={styles.rankRow}>
              <div className={styles.rankBadge}>4th</div>
              <div className={styles.rankName}>{placements.fourth}</div>
            </div>
            <div className={styles.rankRow}>
              <div className={styles.rankBadge}>5-6</div>
              <div className={styles.rankName}>
                {placements.fifthToSixth.join(" • ")}
              </div>
            </div>
            <div className={styles.rankRow}>
              <div className={styles.rankBadge}>7-8</div>
              <div className={styles.rankName}>
                {placements.seventhToEighth.join(" • ")}
              </div>
            </div>
            <div className={styles.rankRow}>
              <div className={styles.rankBadge}>9-12</div>
              <div className={styles.rankName}>
                {placements.ninthToTwelfth.join(" • ")}
              </div>
            </div>
            <div className={styles.rankRow}>
              <div className={styles.rankBadge}>13-16</div>
              <div className={styles.rankName}>
                {placements.thirteenthToSixteenth.join(" • ")}
              </div>
            </div>
          </div>
        </div>

        {/* Grand Final banner stays in normal width */}
        <GrandFinalCenter
          wbChampion={wbFinalWinner}
          lbChampion={lbFinalWinner}
          champion={grandChampion}
        />
      </div>

      {/* ===== WINNERS BRACKET: FULL SECTION (NO contentWrap) ===== */}
      <Bracket16 data={bracketData} />

      {/* ===== LOSERS BRACKET BACK IN NORMAL WIDTH ===== */}
      <div className={styles.contentWrap}>
        <div style={{ marginTop: "40px" }}>
          <LosersBracket16
            r1={lb_r1}
            r2={lb_r2}
            r3a={lb_r3a}
            r3b={lb_r3b}
            r4={lb_r4}
            lbFinal={lb_final}
            lbWinner={lb_winner}
          />
        </div>
      </div>
    </div>
  );
}
